#################################
# TOML Encodings are explained in the following example for 'n'
#
# Each character is represented by an array of 6 total elements
# split between 2 subarrays of 3 elements each
#
# * is dot, . is no dot
#
# n: * *
#    . *
#    * .
#
# Split in half vertically and assign to seperate sub arrays
#
#          Array 0     Array 1
# Index 0     *           *
# Index 1     .           *
# Index 2     *           .
#
# Dots are represented by a 1, no dot is represented by a 0
#
#######################

# * .
# . .
# . .
a = [ [1, 0, 0], [0, 0, 0] ]

# * .
# * .
# . .
b = [ [1, 1, 0], [0, 0, 0] ]

# * *
# . .
# . .
c = [ [1, 0, 0], [1, 0, 0] ]

d = [ [1, 0, 0], [1, 1, 0] ]
e = [ [1, 0, 0], [0, 1, 0] ]
f = [ [1, 1, 0], [1, 0, 0] ]
g = [ [1, 1, 0], [1, 1, 0] ]
h = [ [1, 1, 0], [0, 1, 0] ]
i = [ [0, 1, 0], [1, 0, 0] ]
j = [ [0, 1, 0], [1, 1, 0] ]
k = [ [1, 0, 1], [0, 0, 0] ]
l = [ [1, 1, 1], [0, 0, 0] ]
m = [ [1, 0, 1], [1, 0, 0] ]
n = [ [1, 0, 1], [1, 1, 0] ]
o = [ [1, 0, 1], [0, 1, 0] ]
p = [ [1, 1, 1], [1, 0, 0] ]
q = [ [1, 1, 1], [1, 1, 0] ]
r = [ [1, 1, 1], [0, 1, 0] ]
s = [ [0, 1, 1], [1, 0, 0] ]
t = [ [0, 1, 1], [1, 1, 0] ]
u = [ [1, 0, 1], [0, 0, 1] ]
v = [ [1, 1, 1], [0, 0, 1] ]
w = [ [0, 1, 0], [1, 1, 1] ]
x = [ [1, 0, 1], [1, 0, 1] ]
y = [ [1, 0, 1], [1, 1, 1] ]
z = [ [1, 0, 1], [0, 1, 1] ]
