[STEPPERS]
STEPPER_DEGREES=1.8
MICROSTEPS=4

[SOLENOIDS]
# whether or not the solenoids fire in serial (one after another) or all at the same time
SERIAL_SOLENOIDS=true
# how long to wait after firing a solenoid
SOL_PAUSE=0.5
# PWM duty cycle (0.0-100.0)
SOL_DUTY_CYCLE=60
# PWM frequency (Hz)
SOL_PWM_FREQ=800

# pins are in BCM numbering
[PINS]
SOL_0_PIN=27
SOL_1_PIN=23
SOL_2_PIN=17
BUTTON_PIN=20

# all sizes in millimeters
[SIZES]
PAPER_STEPPER_DIAMETER=28.47
HEAD_STEPPER_DIAMETER=17.65
HALF_CHAR_STEPS=2.68
SPACE_STEPS=10.461
RESET_STEPS=45.59
NEW_LINE_STEPS=11.4808
EJECT_STEPS=279
# how many characters can be printed horizontally per line
CHARS_PER_LINE=30
