"character" = "\"*"
"day"       = "\"d"
"ever"      = "\"e"
"father"    = "\"f"
"here"      = "\"h"
"know"      = "\"k"
"lord"      = "\"l"
"mother"    = "\"m"
"name"      = "\"n"
"one"       = "\"o"
"ought"     = "\"\\"
"part"      = "\"p"
"question"  = "\"q"
"right"     = "\"r"
"some"      = "\"s"
"there"     = "\"!"
"through"   = "\"?"
"time"      = "\"t"
"under"     = "\"u"
"where"     = "\":"
"work"      = "\"w"
"young"     = "\"y"
