"be"     = "2"
"con"    = "3"
"dis"    = "4"
"ea"     = "1"
"en"     = "5"
"enough" = "5"
"his"    = "8"
"in"     = "9"
"was"    = "0"
"were"   = "7"
"bb"     = "2"
"cc"     = "3"
"ff"     = "6"
"gg"     = "7"
