about = "ab"
after = "af"
again = "ag"
against = "ag"
all = "al"
also = "al"
always = "alw"
and = "&"
animal = "an"
answer = "ans"
april = "apr"
area = "ar"
away = "aw"
back = "b"
because = "b"
before = "bf"
between = "bt"
book = "bk"
but = "bt"
by = "by"
can = "c"
cannot = "cnt"
children = "ch"
class = "cl"
come = "co"
company = "cp"
correct = "cor"
could = "cd"
course = "crs"
day = "dy"
different = "dft"
district = "dis"
do = "d"
doe = "do"
english = "eng"
family = "fam"
federal = "fed"
few = "few"
for = "4"
friend = "frd"
from = "fm"
get = "gt"
go = "go"
good = "gd"
have = "hv"
home = "hm"
i = "i"
important = "imp"
inside = "in"
interest = "int"
into = "into"
is = "is"
it = "it"
its = "its"
january = "jan"
july = "jul"
june = "jun"
know = "kno"
last = "lst"
man = "mn"
march = "mar"
may = "may"
more = "mr"
mother = "mth"
name = "nm"
not = "nt"
nothing = "nth"
of = "o"
one = "1"
only = "only"
open = "opn"
people = "ppl"
place = "plc"
question = "qst"
really = "rlly"
right = "rt"
school = "sch"
september = "sept"
that = "th"
the = "t"
there = "thr"
they = "th"
this = "ths"
time = "tm"
to = "2"
together = "tgthr"
under = "udr"
very = "vry"
we = "w"
with = "w"
without = "w/o"
