[strong-contractions]
"and"   = "&"
"for"   = "="
"of"    = "("
"the"   = "!"
"with"  = ")"
"ch"    = "*"
"child" = "*"
"sh"    = "%"
"shall" = "%"
"th"    = "?"
"this"  = "?"
"wh"    = ":"
"which" = ":"
"ou"    = "\\"
"out"   = "\\"
"st"    = "/"
"still" = "/"
"ar"    = ">"
"ed"    = "$"
"er"    = "]"
"ing"   = "+"
"gh"    = "<"
"ow"    = "["

[shortforms]
about = "ab"
above = "abv"
according = "ac"
across = "acr"
after = "af"
afternoon = "afn"
afterward = "afw"
again = "ag"
against = "ag/"
almost = "alm"
already = "alr"
also = "al"
although = "al?"
altogether = "alt"
always = "alw"
because = "2c"
before = "2f"
behind = "2h"
below = "2l"
beneath = "2n"
beside = "2s"
between = "2t"
beyond = "2y"
blind = "bl"
braille = "brl"
children = "*n"
conceive = "3cv"
conceiving = "3cvg"
could = "cd"
deceive = "dcv"
deceiving = "dcvg"
declare = "dcl"
declaring = "dclg"
either = "ei"
first = "f/"
friend = "fr"
good = "gd"
great = "grt"
herself = "h}f"
him = "hm"
himself = "hmf"
immediate = "imm"
its = "xs"
itself = "xf"
letter = "lr"
little = "ll"
much = "m*"
must = "m/"
myself = "myf"
necessary = "nec"
neither = "nei"
oneself = "\"of"
ourselves = "\\rvs"
paid = "pd"
perceive = "p}cv"
perceiving = "p}cvg"
perhaps = "p}h"
quick = "qk"
receive = "rcv"
receiving = "rcvg"
rejoice = "rjc"
rejoicing = "rjcg"
said = "sd"
should = "%d"
such = "s*"
themselves = "!mvs"
thyself = "?yf"
today = "td"
together = "tgr"
tomorrow = "tm"
tonight = "tn"
would = "wd"
your = "yr"
yourself = "yrf"
yourselves = "yrvs"

[dot-45]
"these" = "^!"
"those" = "^?"
"upon"  = "^u"
"whose" = "^:"
"word"  = "^w"

[dot-456]
"cannot" = "_c"
"had"    = "_h"
"many"   = "_m"
"spirit" = "_s"
"their"  = "_!"
"world"  = "_w"

[lower-contractions]
"be"     = "2"
"con"    = "3"
"dis"    = "4"
"ea"     = "1"
"en"     = "5"
"enough" = "5"
"his"    = "8"
"in"     = "9"
"was"    = "0"
"were"   = "7"
"bb"     = "2"
"cc"     = "3"
"ff"     = "6"
"gg"     = "7"

[alphabetic-word-signs]
"but"       = "b"
"can"       = "c"
"do"        = "d"
"every"     = "e"
"from"      = "f"
"go"        = "g"
"have"      = "h"
"just"      = "j"
"knowledge" = "k"
"like"      = "l"
"more"      = "m"
"not"       = "n"
"people"    = "p"
"quite"     = "q"
"rather"    = "r"
"so"        = "s"
"that"      = "t"
"us"        = "u"
"very"      = "v"
"will"      = "w"
"it"        = "x"
"you"       = "y"
"as"        = "z"

[dot-5]
"character" = "\"*"
"day"       = "\"d"
"ever"      = "\"e"
"father"    = "\"f"
"here"      = "\"h"
"know"      = "\"k"
"lord"      = "\"l"
"mother"    = "\"m"
"name"      = "\"n"
"one"       = "\"o"
"ought"     = "\"\\"
"part"      = "\"p"
"question"  = "\"q"
"right"     = "\"r"
"some"      = "\"s"
"there"     = "\"!"
"through"   = "\"?"
"time"      = "\"t"
"under"     = "\"u"
"where"     = "\":"
"work"      = "\"w"
"young"     = "\"y"
