"." = "4"
"?" = "8"
"!" = "6"
"," = "1"
":" = "3"
";" = "2"
"/" = "_/"
"…" = "444"
"-" = "-"
"—" = ",-"
"“" = "8"
"”" = "0"
"‘" = ",8"
"’" = ",0"
"(" = "\"<"
")" = "\">"
"[" = ".<"
"]" = ".>"
"{" = "_<"
"}" = "_>"
"@" = "`a"
"#" = "_?"
"_" = ".-"
"'" = "7"
"\"" = "77"
"°" = "^j"
"%" = ".0"
