"and"   = "&"
"for"   = "="
"of"    = "("
"the"   = "!"
"with"  = ")"
"ch"    = "*"
"child" = "*"
"sh"    = "%"
"shall" = "%"
"th"    = "?"
"this"  = "?"
"wh"    = ":"
"which" = ":"
"ou"    = "\\"
"out"   = "\\"
"st"    = "/"
"still" = "/"
"ar"    = ">"
"ed"    = "$"
"er"    = "]"
"ing"   = "+"
"gh"    = "<"
"ow"    = "["
